name: rem_cli
description: CLI tool to initialize REM project template
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  dcli: ^4.0.1
  path: ^1.9.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1

dev_dependencies:
  lints: ^5.0.0
