name: shared
description: Shared code between arona and plana
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Core
  json_annotation: ^4.9.0

  # Networking
  dio: ^5.9.0

  # State Management
  get: ^4.7.3

  # UI
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.1
  gap: ^3.0.1
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0+1

  # Utils
  device_info_plus: ^12.3.0
  envied: ^1.1.1
  flutter_secure_storage: ^10.0.0
  intl: ^0.20.2
  jiffy: ^6.4.3
  local_auth: ^3.0.0
  requests_inspector: ^5.2.2

dev_dependencies:
  build_runner: ^2.11.0
  envied_generator: ^1.1.1
  json_serializable: ^6.11.2
  test: ^1.26.3

