name: arisu
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  jaspr: ^0.21.7
  jaspr_router: ^0.8.0
  http: ^1.2.0
  envied: ^1.0.0

dev_dependencies:
  build_runner: ^2.6.0
  envied_generator: ^1.0.0
  jaspr_web_compilers: ^4.3.2+1
  jaspr_builder: ^0.21.7
  jaspr_lints: ^0.5.1
  lints: ^5.0.0

jaspr:
  mode: server

