services:
  db:
    image: postgres:15-alpine
    container_name: plana-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=rem_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - plana-network

  plana:
    build:
      context: ..
      dockerfile: api_server/Dockerfile
    container_name: plana
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    networks:
      - plana-network

networks:
  plana-network:
    name: plana-network
    driver: bridge
