name: plana
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  bcrypt: ^1.1.3
  dart_frog: ^1.2.6
  dart_jsonwebtoken: ^3.3.1
  decimal: ^3.1.1
  dio: ^5.9.0
  envied: ^1.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  postgres: ^3.0.2
  shared:
    path: ../packages/shared
  uuid: ^4.5.1
  validators2: ^5.0.0

dev_dependencies:
  build_runner: ^2.4.13
  dart_frog_lint: ^0.1.0
  envied_generator: ^1.1.1
  json_serializable: ^6.9.2
  mocktail: ^1.0.4
  test: ^1.25.11
